// SPDX-FileCopyrightText: 2022 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Illiux <newoutlook@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 Júlio César Ueti <52474532+Mirino97@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 2024 Crotalus <Crotalus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        private List<(string, NetEntity)> Antagonist_warps = new();
        private List<(string, NetEntity)> Living_warps = new();
        private List<(string, NetEntity)> Ghost_warps = new();
        private List<(string, NetEntity)> Misc_warps = new();
        private string _searchText = string.Empty;

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        }

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            Antagonist_warps = [];
            Living_warps = [];
            Ghost_warps = [];
            Misc_warps = [];
            foreach(GhostWarp point in warps)
            {
                if (point.Mob)
                {
                    var name = point.DisplayName + (point.Followers > 0 ? " f: " + point.Followers : "");
                    if (point.Antagonist)
                    {
                        Antagonist_warps.Add((name, point.Entity));
                    }
                    else if(!point.Player_ghost)
                    {
                        Living_warps.Add((name, point.Entity));
                    }
                    else
                    {
                        Ghost_warps.Add((name, point.Entity));
                    }
                }
                else
                {
                    var name = Loc.GetString("ghost-target-window-current-button", ("name", point.DisplayName));
                    Misc_warps.Add((name, point.Entity));
                }
            }
        }

        public void Populate()
        {
            AntagonistContainer.DisposeAllChildren();
            LivingContainer.DisposeAllChildren();
            GhostContainer.DisposeAllChildren();
            MiscContainer.DisposeAllChildren();
            AddButtons();
        }

        private void AddButtons()
        {
            var total_antagonist_length = 0; // No we can't just set it as .length
            foreach (var (name, warpTarget) in Antagonist_warps)
            {
                var currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Top,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(20, 20),
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);
                if(currentButtonRef.Visible)
                {
                    total_antagonist_length++;
                }

                AntagonistContainer.AddChild(currentButtonRef);
            }
            AntagonistHeading.Title = "Antagonists - (" + total_antagonist_length + ")";
            AntagBox.Visible = total_antagonist_length > 0 ? true : false;
            var total_living_length = 0;
            foreach (var (name, warpTarget) in Living_warps)
            {
                var currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Top,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(20, 20),
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);
                if(currentButtonRef.Visible)
                {
                    total_living_length++;
                }

                LivingContainer.AddChild(currentButtonRef);
            }
            LivingHeading.Title = "Alive - (" + total_living_length + ")";
            var total_ghost_length = 0;
            foreach (var (name, warpTarget) in Ghost_warps)
            {
                var currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Top,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(20, 20),
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);
                if(currentButtonRef.Visible)
                {
                    total_ghost_length++;
                }

                GhostContainer.AddChild(currentButtonRef);
            }
            GhostHeading.Title = "Ghosts - (" + total_ghost_length + ")";
            var total_misc_length = 0; // No we can't just set it as _warps.length
            foreach (var (name, warpTarget) in Misc_warps)
            {
                var currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Top,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(20, 20),
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);
                if(currentButtonRef.Visible)
                {
                    total_misc_length++;
                }

                MiscContainer.AddChild(currentButtonRef);
            }
            MiscHeading.Title = "Misc - (" + total_misc_length + ")";
        }

        private bool ButtonIsVisible(Button button)
        {
            return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void UpdateVisibleButtons()
        {
            foreach (var child in AntagonistContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            foreach (var child in LivingContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            foreach (var child in GhostContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            foreach (var child in MiscContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            UpdateVisibleButtons();
            // Reset scroll bar so they can see the relevant results.
            GhostScroll.SetScrollValue(Vector2.Zero);
        }
    }
}
